### ISSUE TITLE
Find a way to set the color of drawable for api<21

### ISSUE THREAD

**Issue by Gianlu94** [HyperTesto/QuestEasy#1]
The setTint method works only for api > 21. For api < 21 I tried with setColorFilter but It seems to set only the color of the letter.So I tried to extend TextDrawable class in ordet to implement a method that would allow me to solve the problem, but the TextDrawable Class defined by the author doesn't permit any forms of extension by others.

**Comment by HyperTesto** [comment]
Color.parseColor("#AE6118");
Does it works?

**Comment by HyperTesto** [comment]
d553d335f1cb72a330247f37a29895ad96a51f95
Test with this and report here
